Repository w3c/html, pull requests merged in 2018-03, with the labels that each got.

#1269 correct some definition links
  sections/browsers.include
Labels: editorial, linking

#1272 Fix PING layout issue
  sections/iana.include
Labels: editorial

#1268 fix remote-playback interface link
  sections/semantics-embedded-content.include
  single-page.bs
Labels: editorial, linking

#1275 simplify condition in ping processing
  sections/semantics-links.include
Labels: editorial, linking

#1284 fixes #1258 - provide picture example
  sections/semantics-embedded-content.include
Labels: editorial

#1278 Remove onshow
  sections/attributes.include
  sections/browsers.include
  sections/dom.include
  sections/webappapis.include
Labels: editorial, linking

#1267 Add bdo example
  sections/semantics-textlevel.include
Labels: editorial, i18n-comment

#1273 UTF-8 All The Things
  sections/attributes.include
  sections/changes.include
  sections/iana.include
  sections/obsolete.include
  sections/semantics-document-metadata.include
  sections/semantics-scriptings.include
Labels: i18n-tracking

#1310 Explain the name attribute of object better
  sections/acknowledgements.include
  sections/semantics-embedded-content.include
Labels: editorial, enhancement
