Repository w3c/html, pull requests merged in 2018-06, with the labels that each got.

#1454 fix wrong position of the Macintosh Uniform Type Identifier for html
  sections/changes.include
  sections/iana.include
Labels: editorial

#1444 update to prose
  sections/introduction.include
Labels: editorial

#1471 HTMLAllCollection getter should not return null
  sections/infrastructure.include
Labels: editorial

#1470 tweak obsolete section on javascript
  sections/obsolete.include
Labels: editorial

#1448 add slot example
  images/rendered-custom-element.jpg
  sections/acknowledgements.include
  sections/semantics-scriptings.include
Labels: editorial

#1462 add disableRemotePlayback to audio and video attr listing
  sections/semantics-embedded-content.include
Labels: editorial

#1479 set-cookie meta has no effect
  sections/changes.include
  sections/semantics-document-metadata.include
Labels: WHATWG Port, match reality better, security

#1467 add in canonical
  sections/changes.include
  sections/semantics-document-metadata.include
  sections/semantics-links.include
Labels: not ready for merge

#1427 Add prose / example for headers attribute
  sections/semantics-tabular-data.include
Labels: editorial

#1491 Editorial updates to header
  sections/semantics-sections.include
Labels: editorial

#1489 define HTMLOrSVGElement mixin
  .travis.yml
  sections/changes.include
  sections/dom.include
  sections/infrastructure.include
  sections/rendering.include
  single-page.bs
Labels: Dependency Request, WHATWG Port
