Repository w3c/html, pull requests merged in 2018-02, with the labels that each got.

#1206 Editorial: remove ascii art in source files -
  sections/attributes.include
  sections/element-content-categories.include
  sections/element-interfaces.include
  sections/elements.include
  sections/events.include
  sections/semantics-sections.include
Labels: editorial

#1199 Improve all examples
  sections/acknowledgements.include
  sections/browsers.include
  sections/dom.include
  sections/editing.include
  sections/infrastructure.include
  sections/introduction.include
  sections/obsolete.include
  sections/rendering.include
  sections/semantics-common-idioms.include
  sections/semantics-document-metadata.include
  sections/semantics-edits.include
  sections/semantics-embedded-content.include
  sections/semantics-forms.include
  sections/semantics-grouping-content.include
  sections/semantics-interactive-elements.include
  sections/semantics-links.include
  sections/semantics-root.include
  sections/semantics-scriptings.include
  sections/semantics-sections.include
  sections/semantics-tabular-data.include
  sections/semantics-textlevel.include
  sections/semantics.include
  sections/syntax.include
  sections/webappapis.include
Labels: editorial

#1204 Caption end tag can be ommitted
  sections/changes.include
  sections/semantics-tabular-data.include
Labels: match reality better, substantive

#1210 Update semantics-edits.include header
  sections/semantics-edits.include
Labels: editorial

#1203 Update comments in some source files
  sections/browsers.include
  sections/dom.include
  sections/editing.include
  sections/iana.include
  sections/infrastructure.include
  sections/obsolete.include
  sections/rendering.include
  sections/semantics-common-idioms.include
  sections/semantics-document-metadata.include
Labels: editorial

#1213 Update header comment
  sections/semantics-embedded-content.include
Labels: editorial

#1223 Replace "&#x0058;&#x0058;&#x0058;" with "issue"
  sections/infrastructure.include
  sections/introduction.include
  styles/styles-html.css
Labels: editorial

#1227 Explanatory text for alternate CSS
  sections/semantics-links.include
Labels: editorial

#1218 Fix Bikeshed Warnings
  sections/browsers.include
  sections/changes.include
  sections/elements.include
  sections/infrastructure.include
  sections/rendering.include
  sections/semantics-grouping-content.include
  sections/semantics-scriptings.include
  sections/syntax.include
  sections/webappapis.include
  single-page.bs
Labels: editorial

#1235 fix link warnings / whitespace
  sections/webappapis.include
Labels: editorial, linking

#1238 Updates the DL definition
  sections/semantics-grouping-content.include
Labels: editorial

#1228 Multilingual quotes
  includes/cldr.include
  sections/rendering.include
Labels: editorial

#1248 add examples to u
  sections/semantics-textlevel.include
Labels: editorial

#1251 clean up from #1248
  sections/semantics-textlevel.include
Labels: editorial

#1257 fixes #1243 - Add refrences to alt with no value
  sections/semantics-embedded-content.include
Labels: editorial

#1261 link "accessible name"
  single-page.bs
Labels: editorial, linking

#1265 fix roles
  sections/semantics-textlevel.include
Labels: bug
