Repository w3c/html, pull requests merged in 2018-04, with the labels that each got.

#1323 add customElements to Window object
  sections/browsers.include
  sections/changes.include
Labels: linking, match reality better, not ready for merge, substantive

#1320 add example for the data element
  sections/semantics-textlevel.include
Labels: editorial

#1332 Ignore DOCTYPE in srcdoc
  sections/acknowledgements.include
  sections/changes.include
  sections/semantics-embedded-content.include
Labels: substantive

#1352 fix aria role classification in <thead>/<tfoot> element boxes
  sections/semantics-tabular-data.include
Labels: bug, editorial

#1322 tweaks for ismap
  sections/acknowledgements.include
  sections/semantics-embedded-content.include
  sections/semantics-textlevel.include
Labels: a11y, editorial, linking

#1354 Example for bdi element
  sections/semantics-textlevel.include
Labels: editorial

#1369 add notes to refer to other examples for td & tr elements
  sections/semantics-tabular-data.include
Labels: not ready for merge

#1366 Adds capture attribute
  sections/acknowledgements.include
  sections/changes.include
  sections/semantics-forms.include
Labels: substantive

#1331 Focus the dialog instead of the first item
  includes/status.include
  sections/acknowledgements.include
  sections/changes.include
  sections/semantics-interactive-elements.include
Labels: at risk, needs tests, not ready for merge, substantive

#1378 Added HTML only example for the video element.
  sections/semantics-embedded-content.include
Labels: editorial

#1399 make longdesc on <img> not obsolete anymore
  sections/obsolete.include
Labels: bug, editorial

#1398 fix #1397
  sections/semantics-grouping-content.include
Labels: editorial

#1396 So 1347 1348
  sections/semantics-tabular-data.include
Labels: editorial

#1379 Minor picture element changes
  .gitignore
  sections/semantics-embedded-content.include
Labels: editorial

#1394 refer to existing tbody examples
  sections/semantics-tabular-data.include
Labels: editorial

#1329 define the :defined pseudo-class
  includes/status.include
  sections/changes.include
  sections/semantics.include
  single-page.bs
Labels: at risk

#1400 links in the section about obsolete features
  sections/obsolete.include
Labels: editorial

#1403 define slot element
  sections/changes.include
  sections/elements.include
  sections/semantics-scriptings.include
  single-page.bs
Labels: substantive

#1402 Describe slot attribute
  sections/dom.include
  single-page.bs
Labels: editorial, linking

#1411 clean up img/decoding
  includes/status.include
  sections/attributes.include
  sections/semantics-embedded-content.include
Labels: editorial

#1413 link rel="external" is not allowed...
  sections/semantics-links.include
Labels: editorial
